networks:
    traefik-network:
        driver: bridge

include:
    - ./API_GATEWAY/docker-compose.yaml
    - ./FRONT/docker-compose.yaml
    - ./COMMANDE/docker-compose.yaml
    - ./PANIER/docker-compose.yml
    - ./LOKI/docker-compose.yaml
    - ./RABBITMQ/docker-compose.yaml