networks:
    traefik-network:
        driver: bridge
    api-gateway-network:
        driver: bridge
    commande-network:
        driver: bridge
    front-network:
        driver: bridge
    panier-network:
        driver: bridge
    loki-network:
        driver: bridge
    rabbitmq-network:
        driver: bridge

include:
    - ./API_GATEWAY/docker-compose.yaml
    - ./FRONT/docker-compose.yaml
    - ./COMMANDE/docker-compose.yaml
    - ./PANIER/docker-compose.yml
    - ./LOKI/docker-compose.yaml
    - ./RABBITMQ/docker-compose.yaml
    - ./FAKE_SERVICE/docker-compose.yaml