version: '3'

services:
  reverse-proxy:
    image: traefik:v3.2
    container_name: Breizhsport_API_GATEWAY
    # command: --api.insecure=true --providers.docker
    command: --api.insecure --providers.docker
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
