services:
  api-gateway:
    image: traefik:v3.2
    container_name: api-gateway
    # command: --api.insecure=true --providers.docker
    command: --api.insecure --providers.docker
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
