global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: DEBUG
accessLog: {}
tracing: {}
metrics:
  addInternals: true
api:
  dashboard: true
  insecure: true
entryPoints:
  web:
    address: :80
  websecure:
    address: :443
providers:
  file:
    directory: /etc/traefik
http:
  middlewares:
    test-ratelimit:
      rateLimit:
        average: 100
        burst: 200
    requireJWT:
      headers:
        customRequestHeaders:
          Authorization: ""
    # authSources:
    #   jwtSource:
    #     jwt:
    #       jwksFile: https://crisp-tetra-47.clerk.accounts.dev/.well-known/jwks.json
    testHeader:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - OPTIONS
        accessControlAllowHeaders: "*"
        accessControlAllowOriginList:
          - "*"
        accessControlMaxAge: 100
        addVaryHeader: true
    test-retry:
      retry:
        attempts: 4
        initialInterval: 100ms
  services:
    Breizhsport_PANIER:
      loadBalancer:
        servers:
        - url: "http://PANIER:3000/"
    Breizhsport_COMMANDE:
      loadBalancer:
        servers:
        - url: "http://www_symfony:80/"
  routers:
    panier:
      entryPoints:
        - web
        - websecure
      rule: "PathPrefix(`/panier`)"
      service: Breizhsport_PANIER
    commande:
      entryPoints:
        - web
        - websecure
      rule: "PathPrefix(`/order`)"
      service: Breizhsport_COMMANDE