name: breizhsport_panier

services:
    backend_panier:
        container_name: PANIER
        image: flobomax/breizhsport_panier
        ports:
            - "3001:3000"
        depends_on:
            - database_panier
            - rabbitmq
        networks:
            - breizhsport_panier-networks

    database_panier:
        container_name: PANIER_DB
        image: mongo
        ports:
            - "27017:27017"
        networks:
            - breizhsport_panier-networks
        volumes:
            - ./data/db_panier:/data/db

networks:
    breizhsport_panier-networks:
      driver: bridge