name: breizhsport_panier

services:
    backend_panier:
        container_name: PANIER
        image: flobomax/breizhsport_panier
        ports:
            - "3001:3000"
        depends_on:
            database_panier:
                condition: service_started
            rabbitmq:
                condition: service_healthy
        networks:
            - breizhsport_panier-networks
            - traefik-network

    database_panier:
        container_name: PANIER_DB
        image: mongo
        ports:
            - "27017:27017"
        networks:
            - breizhsport_panier-networks
        volumes:
            - ./data/db_panier:/data/db

networks:
    breizhsport_panier-networks:
        driver: bridge
    traefik-network:
        external: true